import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Maaz-Portfolio",
//   description: "Generated by create next app",
// };
export const metadata = {
  title: "Abdul Maaz Qureshi | Full-Stack Developer Portfolio",
  description: "Portfolio of Abdul Maaz Qureshi – showcasing projects, skills in web development, React, Next.js, and more. Explore my work and get in touch!",
  // keywords: "Abdul Maaz, Portfolio, Full-Stack Developer, React, Next.js, JavaScript, Web Development, Projects",
  // authors: [{ name: "Abdul Maaz Qureshi", url: "https://your-portfolio-url.com" }],
  // viewport: "width=device-width, initial-scale=1.0",
  // themeColor: "#0D3B66", // can match your favicon color
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
